language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COVERAGE=0

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COVERAGE=1
fast_finish: true

before_install:
  - if [[ $COVERAGE = 0 ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - composer run test:ci

after_script:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
